// Generated by gencpp from file arduino/rc.msg
// DO NOT EDIT!


#ifndef ARDUINO_MESSAGE_RC_H
#define ARDUINO_MESSAGE_RC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arduino
{
template <class ContainerAllocator>
struct rc_
{
  typedef rc_<ContainerAllocator> Type;

  rc_()
    : Steering(0.0)
    , Throttle(0.0)
    , Button1(0)
    , Button2(0)  {
    }
  rc_(const ContainerAllocator& _alloc)
    : Steering(0.0)
    , Throttle(0.0)
    , Button1(0)
    , Button2(0)  {
  (void)_alloc;
    }



   typedef float _Steering_type;
  _Steering_type Steering;

   typedef float _Throttle_type;
  _Throttle_type Throttle;

   typedef int32_t _Button1_type;
  _Button1_type Button1;

   typedef int32_t _Button2_type;
  _Button2_type Button2;





  typedef boost::shared_ptr< ::arduino::rc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arduino::rc_<ContainerAllocator> const> ConstPtr;

}; // struct rc_

typedef ::arduino::rc_<std::allocator<void> > rc;

typedef boost::shared_ptr< ::arduino::rc > rcPtr;
typedef boost::shared_ptr< ::arduino::rc const> rcConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arduino::rc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arduino::rc_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arduino::rc_<ContainerAllocator1> & lhs, const ::arduino::rc_<ContainerAllocator2> & rhs)
{
  return lhs.Steering == rhs.Steering &&
    lhs.Throttle == rhs.Throttle &&
    lhs.Button1 == rhs.Button1 &&
    lhs.Button2 == rhs.Button2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arduino::rc_<ContainerAllocator1> & lhs, const ::arduino::rc_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arduino

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arduino::rc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduino::rc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arduino::rc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arduino::rc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino::rc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino::rc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arduino::rc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85d8f319b6d9e8b597120546faa1bbf9";
  }

  static const char* value(const ::arduino::rc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85d8f319b6d9e8b5ULL;
  static const uint64_t static_value2 = 0x97120546faa1bbf9ULL;
};

template<class ContainerAllocator>
struct DataType< ::arduino::rc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arduino/rc";
  }

  static const char* value(const ::arduino::rc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arduino::rc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 Steering\n"
"float32 Throttle\n"
"int32 Button1\n"
"int32 Button2\n"
;
  }

  static const char* value(const ::arduino::rc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arduino::rc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Steering);
      stream.next(m.Throttle);
      stream.next(m.Button1);
      stream.next(m.Button2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arduino::rc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arduino::rc_<ContainerAllocator>& v)
  {
    s << indent << "Steering: ";
    Printer<float>::stream(s, indent + "  ", v.Steering);
    s << indent << "Throttle: ";
    Printer<float>::stream(s, indent + "  ", v.Throttle);
    s << indent << "Button1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Button1);
    s << indent << "Button2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Button2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUINO_MESSAGE_RC_H
